### ISSUE TITLE
CTR parser fails to handle any property that contains a -- prefix.

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud-task-app-starters/composed-task-runner#22]
_From @cppwfs on November 19, 2017 20:59_

If a user attempts to set the command line properties  property in the tasklaunchrequest-transform  using the --properties option at stream deployment time,  the CTR fails to process any entry that contains a `--`.  For example in the following stream:
`time --fixed-delay=30 | tasklaunchrequest-transform --uri=file:///Users/glennrenfro/project/spring-cloud-task-app-starters/composed-task-runner/apps/composedtaskrunner-task/target/composedtaskrunner-task-1.1.0.BUILD-SNAPSHOT.jar | task-launcher-local`

if the user tries to add an argument with the  `--` 
 prefix in the command-line-args like the following: 

```
stream deploy doodle3 --properties "app.tasklaunchrequest-transform.command-line-arguments='--graph=taskfun-AAA&&taskfun-BBB --increment-instance-enabled=true --spring.datasource.url=jdbc:mariadb://localhost:3306/practice --spring.datasource.username=root --spring.datasource.password=password --spring.datasource.driverClassName=org.mariadb.jdbc.Driver' ,app.tasklaunchrequest-transform.uri=file:///Users/glennrenfro/project/spring-cloud-task-app-starters/composed-task-runner/apps/composedtaskrunner-task/target/composedtaskrunner-task-1.1.0.BUILD-SNAPSHOT.jar"
```

we get this stack track:
```
org.springframework.cloud.dataflow.core.dsl.CheckPointedParseException: 168E:(pos 25): arguments not allowed unless parser is in app mode
taskfun-AAA&&taskfun-BBB --increment-instance-enabled=true --spring.datasource.url=jdbc:mariadb://localhost:3306/practice --spring.datasource.username=root --spring.datasource.password=password --spring.datasource.driverClassName=org.mariadb.jdbc.Driver
                        *^

	at org.springframework.cloud.dataflow.core.dsl.Tokens.raiseException(Tokens.java:276) ~[spring-cloud-dataflow-core-1.2.3.RELEASE.jar!/:1.2.3.RELEASE]
	at org.springframework.cloud.dataflow.core.dsl.TaskParser.eatTaskApp(TaskParser.java:215) ~[spring-cloud-dataflow-core-1.2.3.RELEASE.jar!/:1.2.3.RELEASE]
	at org.springframework.cloud.dataflow.core.dsl.TaskParser.parseTaskNode(TaskParser.java:163) ~[spring-cloud-dataflow-core-1.2.3.RELEASE.jar!/:1.2.3.RELEASE]
	at org.springframework.cloud.dataflow.core.dsl.TaskParser.parseFlow(TaskParser.java:173) ~[spring-cloud-dataflow-core-1.2.3.RELEASE.jar!/:1.2.3.RELEASE]
	at org.springframework.cloud.dataflow.core.dsl.TaskParser.parseTaskNode(TaskParser.java:166) ~[spring-cloud-dataflow-core-1.2.3.RELEASE.jar!/:1.2.3.RELEASE]
	at org.springframework.cloud.dataflow.core.dsl.TaskParser.eatSequences(TaskParser.java:115) ~[spring-cloud-dataflow-core-1.2.3.RELEASE.jar!/:1.2.3.RELEASE]
	at org.springframework.cloud.dataflow.core.dsl.TaskParser.parse(TaskParser.java:89) ~[spring-cloud-dataflow-core-1.2.3.RELEASE.jar!/:1.2.3.RELEASE]
	at org.springframework.cloud.task.app.composedtaskrunner.StepBeanDefinitionRegistrar.getTaskApps(StepBeanDefinitionRegistrar.java:132) ~[spring-cloud-starter-task-composedtaskrunner-1.1.0.BUILD-SNAPSHOT.jar!/:1.1.0.BUILD-SNAPSHOT]
	at org.springframework.cloud.task.app.composedtaskrunner.StepBeanDefinitionRegistrar.registerBeanDefinitions(StepBeanDefinitionRegistrar.java:55) ~[spring-cloud-starter-task-composedtaskrunner-1.1.0.BUILD-SNAPSHOT.jar!/:1.1.0.BUILD-SNAPSHOT]
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsFromRegistrars(ConfigurationClassBeanDefinitionReader.java:359) ~[spring-context-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForConfigurationClass(ConfigurationClassBeanDefinitionReader.java:143) ~[spring-context-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitions(ConfigurationClassBeanDefinitionReader.java:116) ~[spring-context-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:320) ~[spring-context-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:228) ~[spring-context-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:270) ~[spring-context-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:93) ~[spring-context-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:687) ~[spring-context-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:525) ~[spring-context-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693) [spring-boot-1.5.6.RELEASE.jar!/:1.5.6.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360) [spring-boot-1.5.6.RELEASE.jar!/:1.5.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) [spring-boot-1.5.6.RELEASE.jar!/:1.5.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118) [spring-boot-1.5.6.RELEASE.jar!/:1.5.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107) [spring-boot-1.5.6.RELEASE.jar!/:1.5.6.RELEASE]
	at org.springframework.cloud.task.app.composedtaskrunner.ComposedtaskrunnerTaskApplication.main(ComposedtaskrunnerTaskApplication.java:29) [classes!/:1.1.0.BUILD-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_144]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_144]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_144]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_144]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [composedtaskrunner-task-1.1.0.BUILD-SNAPSHOT.jar:1.1.0.BUILD-SNAPSHOT]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [composedtaskrunner-task-1.1.0.BUILD-SNAPSHOT.jar:1.1.0.BUILD-SNAPSHOT]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [composedtaskrunner-task-1.1.0.BUILD-SNAPSHOT.jar:1.1.0.BUILD-SNAPSHOT]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [composedtaskrunner-task-1.1.0.BUILD-SNAPSHOT.jar:1.1.0.BUILD-SNAPSHOT]
```

_Copied from original issue: spring-cloud-task-app-starters/app-starters-release#44_

**Comment by sabbyanandan** [comment]
_From @jvmlet on November 19, 2017 22:23_

Another question I have is how should I distinguish the arguments that should be passed to graph and to CTR: `--graph=taskfun-AAA&&taskfun-BBB  - -someTaskFunBbbPropName=5   - -  --increment-instance-enabled=true `

**Comment by sabbyanandan** [comment]
_From @jvmlet on November 19, 2017 22:34_

Another question I have is how should I distinguish the arguments that should be passed to graph and to CTR: --graph=taskfun-AAA&&taskfun-BBB  --someTaskFunBbbPropName=5  --increment-instance-enabled=true

**Comment by cppwfs** [comment]
This is not a CTR issue per se'.  But rather how it should be handled by the TaskLaunchrequestTransform.   Properties that are required for the task apps in the CTR DSL should be passed into the applicationProperties attribute of the TaskLaunchrequestTransform processor.   i.e the task arguments would look something like this `app.tasklaunchrequest-transform.command-line-arguments='--graph=taskfun-AAA&&taskfun-BBB'` and the `applicationProperties` would look something like `app.tasklaunchrequest-transform.application-properties='app.taskfun-BBB. someTaskFunBbbPropName=5'`

With that being said, the `applicationProperties` attribute will have to be added as described in issue: https://github.com/spring-cloud-stream-app-starters/tasklaunchrequest-transform/issues/7.
