### ISSUE TITLE
Job restart creates double parameters for the composed task

### ISSUE THREAD

**Issue by yudaniel** [spring-cloud-task-app-starters/composed-task-runner#96]
### Context
Currently, we are using SCDF v2.2.1 in combination with Openshift v3.11.98. We are using SCDF to schedule our reoccurring ETL jobs, written in Java. To deploy, we use Docker images.

### Problem description
The problem we have is to restart a successfully finished SCDF task.

### Step to reproduce
1. Create a linear (a && b && c) composed task
2. Run the task and let it finish successfully (Status COMPLETED).
3. Rerun the task again

### Expected result
The task starts again from the beginning.

### Actual result
The composed task throws the *JobInstanceAlreadyCompleteException*:
```
java.lang.IllegalStateException: Failed to execute CommandLineRunner
--
  | at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:816) [spring-boot-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
  | at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:797) [spring-boot-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
  | at org.springframework.boot.SpringApplication.run(SpringApplication.java:324) [spring-boot-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
  | at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260) [spring-boot-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
  | at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248) [spring-boot-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
  | at org.springframework.cloud.task.app.composedtaskrunner.ComposedtaskrunnerTaskApplication.main(ComposedtaskrunnerTaskApplication.java:29) [classes!/:2.1.1.RELEASE]
  | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_201]
  | at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_201]
  | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_201]
  | at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_201]
  | at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [composed-task-runner.jar:2.1.1.RELEASE]
  | at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [composed-task-runner.jar:2.1.1.RELEASE]
  | at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [composed-task-runner.jar:2.1.1.RELEASE]
  | at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [composed-task-runner.jar:2.1.1.RELEASE]
  | Caused by: org.springframework.batch.core.repository.JobInstanceAlreadyCompleteException: A job instance already exists and is complete for parameters={-spring.cloud.data.flow.taskappname=composed-task-runner, -spring.cloud.task.executionid=2986, -spring.datasource.username=tms_efa_appl, -graph=kette2-dummy1 && kette2-dummy2, -spring.cloud.data.flow.platformname=default, -spring.datasource.url=jdbc:postgresql://10.107.56.85:5432/tms_efa?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory&currentSchema=efa_scheduling_dev, -spring.datasource.driverClassName=org.postgresql.Driver, -spring.datasource.password=2IT[2{'AfB\|h, -spring.cloud.task.name=kette2, -dataflowServerUri=https://scdf-dev.app.test04.otc-test.sbb.ch:443/ }.  If you want to run this job again, change the parameters.
  | at org.springframework.batch.core.repository.support.SimpleJobRepository.createJobExecution(SimpleJobRepository.java:132) ~[spring-batch-core-4.1.1.RELEASE.jar!/:4.1.1.RELEASE]
  | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_201]
  | at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_201]
  | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_201]
  | at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_201]
  | at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343) ~[spring-aop-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
  | at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198) ~[spring-aop-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
  | at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
  | at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294) ~[spring-tx-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
  | at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98) ~[spring-tx-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
  | at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
  | at org.springframework.batch.core.repository.support.AbstractJobRepositoryFactoryBean$1.invoke(AbstractJobRepositoryFactoryBean.java:181) ~[spring-batch-core-4.1.1.RELEASE.jar!/:4.1.1.RELEASE]
  | at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
  | at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212) ~[spring-aop-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
  | at com.sun.proxy.$Proxy82.createJobExecution(Unknown Source) ~[na:na]
  | at org.springframework.batch.core.launch.support.SimpleJobLauncher.run(SimpleJobLauncher.java:134) ~[spring-batch-core-4.1.1.RELEASE.jar!/:4.1.1.RELEASE]
  | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_201]
  | at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_201]
  | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_201]
  | at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_201]
  | at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343) ~[spring-aop-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
  | at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198) ~[spring-aop-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
  | at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
  | at org.springframework.batch.core.configuration.annotation.SimpleBatchConfiguration$PassthruAdvice.invoke(SimpleBatchConfiguration.java:127) ~[spring-batch-core-4.1.1.RELEASE.jar!/:4.1.1.RELEASE]
  | at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
  | at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212) ~[spring-aop-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
  | at com.sun.proxy.$Proxy84.run(Unknown Source) ~[na:na]
  | at org.springframework.boot.autoconfigure.batch.JobLauncherCommandLineRunner.execute(JobLauncherCommandLineRunner.java:214) ~[spring-boot-autoconfigure-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
  | at org.springframework.boot.autoconfigure.batch.JobLauncherCommandLineRunner.executeLocalJobs(JobLauncherCommandLineRunner.java:186) ~[spring-boot-autoconfigure-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
  | at org.springframework.boot.autoconfigure.batch.JobLauncherCommandLineRunner.launchJobFromProperties(JobLauncherCommandLineRunner.java:172) ~[spring-boot-autoconfigure-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
  | at org.springframework.boot.autoconfigure.batch.JobLauncherCommandLineRunner.run(JobLauncherCommandLineRunner.java:166) ~[spring-boot-autoconfigure-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
  | at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:813) [spring-boot-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
  | ... 13 common frames omitted


```

We are not sure if we are using the composed task wrong?
We would appreciate any help. =)

Thanks.

**Comment by sabbyanandan** [comment]
Hi, @yudaniel. This is by design. CTR is a Spring Batch Job behind the scenes, and to relaunch the same Job, you _must_ launch it with unique arg/param since the successful execution of a job is considered "complete". It is a Spring Batch requirement even.

If you'd like for it to relaunch without a unique arg/param (typically is done), you could set `increment-instance-enabled` to `true,` so that the auto-incrementor will kick-in to relaunch the same Task as desired, as many numbers of times. 

See docs [here](https://docs.spring.io/spring-cloud-dataflow/docs/2.2.1.RELEASE/reference/htmlsingle/#_configuration_options) and [here](https://github.com/spring-cloud-task-app-starters/composed-task-runner/blob/master/spring-cloud-starter-task-composedtaskrunner/README.adoc).

For questions like this, please use Stackoverflow going forward.
